name: PublishVersion
on: 
  push:
    branches:
    - main

  # create release
  #release:
  #  needs: checkout
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: release
  #      uses: ncipollo/release-action@v1
  #      with:
  #        token: ${{ secrets.RELEASE_TOKEN }}
  #        tag: 0.0.2
  #      #uses: release-drafter/release-drafter@v5

  # create docker image and publish to dockerhub
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
        name: Checkout
        
      - name: Build & Push Docker image
        shell: bash
        run: |
          IMAGE_TAG=v.$(date -u +"%Y-%m-%d").${GITHUB_JOB} && \
          docker build -t endriu00/usernamecreatorbot:$IMAGE_TAG . && \
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} && \
          docker push endriu00/usernamecreatorbot:$IMAGE_TAG 

          
        #with:
        #  image: endriu00/usernamecreatorbot
        #  tags: ${IMAGE_TAG}
        #  registry: docker.io
        #  dockerfile: Dockerfile
        #  username: ${{ secrets.DOCKER_USERNAME }}
        #  password: ${{ secrets.DOCKER_PASSWORD }}